FROM scratch

COPY kaptain-user-scripts-${Version}.zip /
COPY kaptain-user-scripts-cli-${Version}.zip /
COPY kaptain-user-scripts-encryption-${Version}.zip /
COPY kaptain-user-scripts-42-${Version}.zip /
