name: Docker Build Dockerfile

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    uses: kube-kaptain/buildon-github-actions/.github/workflows/docker-build-dockerfile.yaml@1.0.91
    permissions:
      contents: write
      packages: write
      checks: write
    with:
      qc-block-slash-containing-branches: true
      qc-block-conventional-commits: true
      hook-pre-tagging-tests-script-sub-path: bin/run-tests.bash
      hook-pre-docker-prepare-script-sub-path: bin/package-for-release.bash
      github-release-verbatim-files: kaptain-out/user-scripts/all/kaptain-user-scripts.zip kaptain-out/user-scripts/cli/kaptain-user-scripts-cli.zip kaptain-out/user-scripts/encryption/kaptain-user-scripts-encryption.zip kaptain-out/user-scripts/util/kaptain-user-scripts-util.zip kaptain-out/user-scripts/build/kaptain-user-scripts-build.zip kaptain-out/user-scripts/42/kaptain-user-scripts-42.zip src/docker/kaptain-completion.bash
